# Generated by Django 5.0.6 on 2024-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandiApp', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='nom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='numero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='prenom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
