# Generated by Django 5.0.6 on 2024-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dandiApp', '0003_remove_contactmessage_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
